### ISSUE TITLE
Provide a minimal SFF file reader PyPi package

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk#10]
It would be good to have a minimal size PyPi package for reading and writing SFF files (not converting from other formats, and not analyzing or visualizing segmentations).

The current sfftk (0.4.1dev0) depends on about 30 additional Python packages.  This makes it unattractive to include in programs like ChimeraX because it increases the distribution size too much.  Many packages, e.g PyWavelets, networkx, mrcfile, matplotlib, pillow, ... surely are not needed to read and write SFF files.

pip3 install sfftk --> Installing collected packages: numpy, six, python-utils, numpy-stl, mrcfile, lxml, PyWavelets, decorator, networkx, cycler, pyparsing, python-dateutil, kiwisolver, matplotlib, pillow, imageio, scipy, scikit-image, simpleparse, ahds, bitarray, h5py, RandomWords, mock, styled, chardet, urllib3, idna, certifi, requests, sfftk

**Comment by paulkorir** [comment]
Done.
