### ISSUE TITLE
Include transformation matrix of segmentation to physical coordinates (Angstroms)

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk#11]
I had difficulties getting the segmentation coordinate system for the 3 segmentation files I tried, two for empiar 10087, and one for emdb 1547.  For 1547 transform id 1 has the transformation but the lattices just references transformId None.  For 10087, there is no transform that indicates the voxel size is 160 Angstroms for the tomograms.  I could get this from the associated density map, but it should be in the segmentation file too.  That way when I open the segmentation first, followed by the tomogram they align and have matching scale.

**Comment by paulkorir** [comment]
Added in https://github.com/emdb-empiar/sfftk-rw/releases/tag/v0.6.0.dev0 to be integrated into `sfftk`.
