### ISSUE TITLE
Provide separate vertex and normal arrays for meshes

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk#12]
The mesh format is both hard and slow to parse with vertices and normals mixed in SFFVertexList.  It would be much easier to use if separate vertex and normal vector lists were provided.   In the current scheme the semantics of which normals go with which vertices is not clear.

**Comment by paulkorir** [comment]
I'll couple this separation with reformatting the vertices and normals into a base64 string.

**Comment by paulkorir** [comment]
Now in https://github.com/emdb-empiar/sfftk-rw/tree/feature/v0.8
