### ISSUE TITLE
Describe surfaces as collections of triangles, not polygons.

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk#13]
Meshes currently consist of a collection of polygons.  This suggests that it is intended to support polygons traced in each plane as is commonly done by hand in IMOD.  In your email (copied below) you say this description of traced curves is not supported by SFF.  In that case I suggest that an SFFMesh  should be a triangulated surface -- ie. only triangles are allowed, not polygons.  All surface descriptions I have ever seen use triangles, polygons only being used to described traced curves.  Using polygons to describe a surface is problematic because the polygon need not be planar and then it becomes ambiguous how to triangulate it.

From: Paul Korir 
Subject: Re: [Segtrans-wg] Fwd: Re: Announcement: Availability of Segmentation Utilities and Resources (Development Release)
Date: October 7, 2019 at 8:03:25 AM PDT
To: Tom Goddard 
Cc: segtrans-wg@ebi.ac.uk

Hi Tom,

In EMDB-SFF a meshes exclusively consists of a set of vertices whose topology is defined by a set of polygons. 

I had tried working with contours (what you refer to as a closed curve) but I got the impression from looking at some libraries and papers that the surface implied by a set of contours is not well defined due to the presence of ambiguous topologies. (I could elaborate at length if needed.) Initially, EMDB-SFF supported contours in addition to meshes, shape primitives and 3D volumes; contours would then be converted to meshes but the effort turned out to be not worth it. Therefore, some tools e.g. IMOD include utilities to do the meshing for you, which is what is suggested if you want to convert from IMOD to EMDB-SFF.

...

To help me keep track of these issues you could also open new issues on Github.

Thanks for your feedback.

Paul K. Korir, PhD

**Comment by paulkorir** [comment]
Now available in `sfftk-rw`. Please open any new issues at https://github.com/emdb-empiar/sfftk-rw/issues
