### ISSUE TITLE
Use underscores in API attribute names as per Python PEP-8 conventions.

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk#14]
The sfftk API uses a mix of attribute names with underscores and ones that are camel case like polygon_ids and numPolygons in SFFPolygonList.  Probably this has to do with the autogenerated code.  But the names should be consistent and Python 3 style guide (PEP 8) has come down in favor of underscores for attribute names and camel case for class names.  I'm not religious about this stuff, but it looks unprofessional, does not inspire faith in the API.

**Comment by paulkorir** [comment]
Done.
