### ISSUE TITLE
Have separate attributes for array or bytes in SFFLattice

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk#15]
SFFLattice.data when I read the EMDB 1547 segmentation was a sequence of bytes (not a numpy array as the docs said), apparently the base64 encoded array for serialization.  By poking around I found that after calling lattice.decode(), lattice.data then becomes a numpy array instead of bytes.  This is confusing.  I'd suggest instead having SFFLattice.data_bytes and SFFLattice.data_array attributes instead of overloading one data attribute.

**Comment by paulkorir** [comment]
Done. Please see sfftk-rw package
