### ISSUE TITLE
Shape geometry export in json version of sff 

### ISSUE THREAD

**Issue by averypennington** [emdb-empiar/sfftk#18]
Hi,
I was exploring using the .json version of the .sff file for geometry, but I don't seem to see the shapes that I've added to a shapePrimitiveList in the json file. Do I need to do anything beyond as_json() to get geometry export to work?
Thanks very much,
Avery

**Comment by paulkorir** [comment]
Hi Avery. 

I'm very sorry for the slow response. For some reason I'm not getting notifications on issues.

I've been working hard on `sfftk-rw` which is a prior package soon to be integrated into `sfftk`. You can find it the latest version on a new branch soon to be release at https://github.com/emdb-empiar/sfftk-rw/tree/feature/v0.8. In this case JSON files have geometry though I'll add a flag to enable it (it should be off by default). 

The whole idea behind JSON is to quickly add/edit/delete annotations without the overhead of dealing with the geometry (which can be enormous).

Thanks so much for your request.

Kind regards,

Paul

**Comment by paulkorir** [comment]
`sfftk-rw` now on PyPI with options for get/omitting geometry.

`pip install sfftk-rw`

However, `sfftk-rw` only works with EMDB-SFF files.
