### ISSUE TITLE
IMODSegmentation constructor misreads object 1 contours as shapes

### ISSUE THREAD

**Issue by bbarad** [emdb-empiar/sfftk#19]
For the attached file, `IMODSegmentation("input_file.mod")` misreads the first of 3 segments as shapes instead of contours, despite `imodinfo input_file.mod` providing the correct information.

Following code reproduces:
```python
import sfftk
from sfftk.formats.mod import IMODSegmentation
mod_seg = IMODSegmentation("input_file.mod")
print(mod_seg.segments)
```

[input_file.mod.zip](https://github.com/emdb-empiar/sfftk/files/4227937/input_file.mod.zip)

**Comment by paulkorir** [comment]
Thanks for reporting this. I'll look into this and do a bugfix.

**Comment by paulkorir** [comment]
I've had a look at the data and two points to consider.

1. When working with IMOD files you need to run `imodmesh` (see https://sfftk.readthedocs.io/en/latest/converting.html#changing-the-primary-descriptor part of the documentation) in order to convert to EMDB-SFF. You can run `sff view --show-chunks file.mod` to see whether you will get any data in the output EMDB-SFF file. Here's what I get with your file:

```
$ sff view --show-chunks input_file.mod
**************************************************
IMOD Segmentation version V1.2
Segmentation name: IMOD-NewModel
Format: IMOD
Primary descriptor: contours
Pixel size: 1.7275995016098022
Pixel units: nm
xmax, ymax, zmax: (960, 928, 300)
No. of segments: 3
**************************************************
b'IMOD' 2
b'OBJT' 1
b'CONT' 6
b'IMAT' 1
b'OBJT' 1
b'CONT' 3
b'IMAT' 1
b'OBJT' 1
b'CONT' 1
b'IMAT' 1
b'VIEW' 2
b'MINX' 1
b'IEOF'
```

2. (1) only works when you have closed contours. From what I see (see https://drive.google.com/open?id=1CPrvpZYlxIr84lcnvMNADy2GjYlsf_5r) these are open contours. I can clearly imagine a use-case where open contours are a valid segmentation representation, which is not currently supported.

**Comment by bbarad** [comment]
I discovered the advice about imodmesh in your documentation. These are segmentations of filaments, so we prefer to keep them as open contours like this, but makes sense to classify it as a potential future feature rather than a current bug. Out of curiosity, do you have a plan to support any way of segmenting 1D filaments in the future? Open contours in IMOD has worked well for us thus far but we would love to standardize.

**Comment by paulkorir** [comment]
We've definitely had another user request such a representation (`line` segment representation collected into a `line_list`). This came up quite recently so we've not yet added it to the specification. I would love to hear more about your 1D use-case and try to get something formal going. Would you be OK to join the working group and propose this? You can find it at https://listserver.ebi.ac.uk/mailman/listinfo/segtrans-wg. 

`imodmesh` can convert open contours into meshes by treating them as tubes. For example you can run:

`imodmesh -t 1,2,3 -d 10 -E -Z 1.0 input_file.mod`

which will convert `OBJT`s 1 to 3 into tubes with a diameter of 10 pixes and cap edges. Once you do the conversion to EMDB-SFF these will now be meshes.

```
~$ imodmesh -t 1,2,3 -d 10 -E -Z 1.0 input_file.mod
Model: input_file.mod
Setting tolerance to 0.25 for point reduction
Meshing object  1
Meshing object  2
Meshing object  3
~$ sff view -C input_file.mod
**************************************************
IMOD Segmentation version V1.2
Segmentation name: IMOD-NewModel
Format: IMOD
Primary descriptor: contours
Auxiliary descriptors: meshes
Pixel size: 1.7275995016098022
Pixel units: nm
xmax, ymax, zmax: (960, 928, 300)
No. of segments: 3
**************************************************
b'IMOD' 2
b'OBJT' 1
b'CONT' 6
b'MESH' 1
b'IMAT' 1
b'MEPA' 1
b'OBJT' 1
b'CONT' 3
b'MESH' 1
b'IMAT' 1
b'MEPA' 1
b'OBJT' 1
b'CONT' 1
b'MESH' 1
b'IMAT' 1
b'MEPA' 1
b'VIEW' 2
b'MINX' 1
b'IEOF'
~$ sff convert -v input_file.mod
Wed Feb 26 15:14:51 2020	Setting output file to input_file.sff
Wed Feb 26 15:14:51 2020	Converting from IMOD file input_file.mod
Wed Feb 26 15:14:51 2020	Created IMODSegmentation object
Wed Feb 26 15:14:51 2020	Exporting to input_file.sff
Wed Feb 26 15:14:51 2020	Done
~$ sff view input_file.sff
**************************************************
EMDB-SFF Segmentation version 0.7.0.dev0
Segmentation name: IMOD-NewModel
Format: XML
Primary descriptor: meshList
No. of segments: 3
**************************************************
```

**Comment by bbarad** [comment]
I am using segmentations to measure distances and angles of approach between cytoskeletal filaments - converting to meshes is OK, but probably unnecessary from a measurements perspective. I'll write a request to the working group!
