### ISSUE TITLE
Convert method - possible bug with args parameter

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [emdb-empiar/sfftk#22]
Dear all,

https://sfftk.readthedocs.io/en/latest/_modules/sfftk/formats/seg.html#SeggerSegmentation.convert
Here convert method requires args parameter to be specified.
When I try to set it as args=None (to simply convert to SFF), an exception occurs:

```
Exception has occurred: AttributeError
'NoneType' object has no attribute 'details'

```

**Comment by paulkorir** [comment]
Fixed in upcoming `v0.6.0` release.
