### ISSUE TITLE
Sfftk bug on Windows

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [emdb-empiar/sfftk#23]
Dear all,

There is a bug with sfftk package. While using it via 'sff' command in terminal, the following error messages pops up:
```
"...\lib\site-packages\sfftk\core\parser.py", line 995, in
parse_args
     return os.EX_OK, None
AttributeError: module 'os' has no attribute 'EX_OK'
```

It is Windows-specific bug.

**Comment by paulkorir** [comment]
Fixed in upcoming `v0.6.0.dev0`
