### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [emdb-empiar/sfftk#26]
Dear all,

There is a typo in docs:
https://sfftk.readthedocs.io/en/latest/developing.html#reading-application-specific-segmentation-files
```
>>> from sfftk.formats.map import MAPSegmentation
>>> map_seg = MAPSegmentation('file.map')
```
Should be `MapSegmentation` instead I think

**Comment by paulkorir** [comment]
Fixed in upcoming `v0.6.0.dev0`.
